include:
  - formelsammlung.md

# This is a comment in a YAML file
# YAML (YAML Ain't Markup Language) is a human-readable data serialization format used for 
#    configuration files and data exchange between programming languages. 
#    It is designed to be easy to read and write, making it a popular choice 
#    for various software applications and services.

# This tells Jekyll to keep that file in the published site so your JavaScript can fetch it.
